# Google Cloud Build configuration for Veridect
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/veridect-app:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/veridect-app:latest',
      '.'
    ]

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/veridect-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/veridect-app:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'veridect-app',
      '--image', 'gcr.io/$PROJECT_ID/veridect-app:$COMMIT_SHA',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--min-instances', '0',
      '--max-instances', '20',
      '--concurrency', '80',
      '--timeout', '900',
      '--set-env-vars', 'NODE_ENV=production',
      '--service-account', 'veridect-service@$PROJECT_ID.iam.gserviceaccount.com'
    ]

# Configure build settings
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Build timeout
timeout: '1200s'

# Artifact registry images
images:
  - 'gcr.io/$PROJECT_ID/veridect-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/veridect-app:latest'