# Google Cloud Build configuration for Veridect
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/veridect:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/veridect:latest'
      - '.'
    timeout: '1200s'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/veridect:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/veridect:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'veridect-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/veridect:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/veridect:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/veridect:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Timeout for the entire build
timeout: '1800s'